"""Ports — the hexagon's boundary. Protocols only; no implementations.

The application depends on these abstractions, never on concrete adapters (DIP).
Each port is narrow and single-purpose (ISP): a new persona evaluator is a new
port + adapter, with zero edits to existing ones (OCP).

`@runtime_checkable` lets the composition root assert an adapter satisfies a port.
"""
from __future__ import annotations

from typing import Protocol, runtime_checkable

from .models import (
    Candidate, CandidateProfile, CoverageAudit, CoverLetterResult, HREval, Job, JDSpec,
    OptimizerLLMOut, RolePersonas, ScreeningResult, Synthesis, Task, TaskStatus, TaskType,
    TechEval, RiskEval,
)


# ---- driven ports: parsing & LLM personas --------------------------------

@runtime_checkable
class TextExtractor(Protocol):
    def extract(self, content: bytes, filename: str) -> str: ...


@runtime_checkable
class GitHubEnricher(Protocol):
    def enrich(self, github_url: str) -> list[dict]: ...


@runtime_checkable
class LinkedInEnricher(Protocol):
    """Distils a LinkedIn-style professional digest from the resume text.
    Resume-only (LinkedIn has no free public API); returns {} when nothing usable."""
    def enrich(self, resume_text: str, profile: CandidateProfile) -> dict: ...


@runtime_checkable
class ProfileExtractor(Protocol):
    def extract(self, resume_text: str) -> CandidateProfile: ...


@runtime_checkable
class JobSpecExtractor(Protocol):
    def extract(self, jd_text: str) -> JDSpec: ...


@runtime_checkable
class Ranker(Protocol):
    def score(self, profile: CandidateProfile, jd: JDSpec) -> float: ...


@runtime_checkable
class TechnicalEvaluator(Protocol):
    def evaluate(self, profile: CandidateProfile, jd: JDSpec, persona: str = "") -> TechEval: ...


@runtime_checkable
class RiskEvaluator(Protocol):
    def evaluate(self, profile: CandidateProfile, persona: str = "") -> RiskEval: ...


@runtime_checkable
class HREvaluator(Protocol):
    def evaluate(self, profile: CandidateProfile, jd: JDSpec, persona: str = "") -> HREval: ...


@runtime_checkable
class Synthesizer(Protocol):
    def synthesize(self, jd: JDSpec, tech: TechEval, risk: RiskEval,
                   hr: HREval | None = None, persona: str = "") -> Synthesis: ...


@runtime_checkable
class CoverageAuditor(Protocol):
    """LLM-as-judge QA pass (§5): checks the evaluation is complete and disciplined.
    Does NOT re-score — reports whether the verdict is safe to surface."""
    def audit(self, jd: JDSpec, profile: CandidateProfile, tech: TechEval | None,
              risk: RiskEval | None, hr: HREval | None, synthesis: Synthesis) -> CoverageAudit: ...


@runtime_checkable
class PersonaDesigner(Protocol):
    """Generates role-specialized agent personas from a JD (the 'subject-matter
    expert' instructions the evaluators adopt for this role)."""
    def design(self, jd_text: str, spec: JDSpec) -> RolePersonas: ...


@runtime_checkable
class ResumeOptimizer(Protocol):
    """Rewrites a resume to maximise ATS keyword coverage for a given JD."""
    def optimize(self, resume_text: str, jd: JDSpec, job_title: str = "") -> OptimizerLLMOut: ...


@runtime_checkable
class CoverLetterWriter(Protocol):
    def write(self, resume_text: str, jd: JDSpec, job_title: str = "", tone: str = "professional") -> str: ...

@runtime_checkable
class GitHubSelector(Protocol):
    def select(self, projects_json: str) -> list[dict]: ...

@runtime_checkable
class LinkedInSelector(Protocol):
    def select(self, resume_text: str) -> dict: ...


@runtime_checkable
class LLMProvider(Protocol):
    """Factory that yields persona adapters bound to a chosen model id. Lets the
    recruiter switch models per run; the application asks for a model by id and
    the provider returns the right adapter (Agno or stub). 'auto' is resolved by
    the application to the configured tier defaults before it reaches here."""
    def profile_extractor(self, model: str) -> ProfileExtractor: ...
    def jd_extractor(self, model: str) -> JobSpecExtractor: ...
    def technical(self, model: str) -> TechnicalEvaluator: ...
    def risk(self, model: str) -> RiskEvaluator: ...
    def hr(self, model: str) -> HREvaluator: ...
    def synthesizer(self, model: str) -> Synthesizer: ...
    def coverage_auditor(self, model: str) -> CoverageAuditor: ...
    def resume_optimizer(self, model: str) -> ResumeOptimizer: ...
    def cover_letter_writer(self, model: str) -> CoverLetterWriter: ...
    def github_selector(self, model: str) -> GitHubSelector: ...
    def linkedin_selector(self, model: str) -> LinkedInSelector: ...


# ---- driven ports: persistence -------------------------------------------

@runtime_checkable
class CandidateRepository(Protocol):
    def add(self, candidate: Candidate) -> None: ...
    def get(self, candidate_id: str) -> Candidate | None: ...
    def find_by_dedup_key(self, dedup_key: str) -> Candidate | None: ...
    def find_by_content_hash(self, content_sha256: str) -> Candidate | None: ...
    def list_all(self) -> list[Candidate]: ...


@runtime_checkable
class JobRepository(Protocol):
    def add(self, job: Job) -> None: ...
    def get(self, job_id: str) -> Job | None: ...
    def list_all(self) -> list[Job]: ...


@runtime_checkable
class ResultRepository(Protocol):
    def upsert(self, result: ScreeningResult) -> None: ...
    def get(self, result_id: str) -> ScreeningResult | None: ...
    def list_for_job(self, job_id: str) -> list[ScreeningResult]: ...
    def set_decision(self, result_id: str, decision: str) -> None: ...


@runtime_checkable
class AuditLog(Protocol):
    """Append-only: every score, rationale, and version is reproducible."""
    def record(self, event: str, **fields) -> None: ...
    def events_for_job(self, job_id: str, limit: int = 200) -> list[dict]: ...


# ---- driven port: durable task queue -------------------------------------

@runtime_checkable
class TaskQueue(Protocol):
    def enqueue(self, task_type: TaskType, payload: dict, staged: bool = False,
                task_id: str | None = None) -> str: ...
    def release(self, task_ids: list[str]) -> int: ...
    def claim_next(self, lease_seconds: int) -> Task | None: ...
    def complete(self, task_id: str, lease_until=None) -> bool: ...
    def heartbeat(self, task_id: str, lease_until, lease_seconds: int): ...
    def fail(self, task_id: str, error: str, retry: bool, lease_until=None) -> None: ...
    def reclaim_expired(self) -> int: ...
    def stats(self) -> dict: ...
    def list_by_status(self, status: TaskStatus, limit: int = 100) -> list[Task]: ...
    def requeue(self, task_id: str) -> bool: ...


# ---- driving port: the use case the UI/worker call inward -----------------

@runtime_checkable
class ScreeningUseCase(Protocol):
    def create_job(self, jd_text: str, persona_model: str = "auto",
                   synth_model: str = "auto") -> Job: ...
    def ingest_resume(self, content: bytes, filename: str, model: str = "auto") -> Candidate: ...
    def screen(self, candidate_id: str, job_id: str, *,
               override_hard_filter: bool = False) -> ScreeningResult: ...
    def enqueue_batch(self, job_id: str, files: list[tuple[bytes, str]]) -> list[str]: ...


# ---- driven ports: observability, memory, throttling ----------------------

@runtime_checkable
class Tracer(Protocol):
    """Records agent-run sessions. start_run opens a trace bound to the current
    thread (contextvar); record_span appends a call; end_run closes it."""
    def start_run(self, kind: str, candidate_id: str = "", job_id: str = "") -> str: ...
    def record_span(self, *, name: str, agent: str = "", model: str = "",
                    latency_ms: float = 0.0, cost_usd: float = 0.0,
                    cache_hit: bool = False, error: str = "") -> None: ...
    def end_run(self, status: str = "done", error: str = "", cache_hit: bool = False) -> None: ...
    def get_run(self, trace_id: str): ...
    def list_runs(self, limit: int = 100) -> list: ...
    def agent_stats(self) -> list[dict]: ...


@runtime_checkable
class AgentMemory(Protocol):
    """Persistent memory the agents consult to ground judgments."""
    def remember(self, *, candidate_id: str, job_id: str, kind: str,
                 content: str, data: dict | None = None) -> None: ...
    def recall_similar_candidates(self, skills: list[str], limit: int = 5) -> list[dict]: ...
    def recall_recruiter_feedback(self, job_id: str = "", limit: int = 10) -> list[dict]: ...


@runtime_checkable
class Throttle(Protocol):
    """Limits LLM call concurrency + rate. Used as a context manager around a call."""
    def __enter__(self): ...
    def __exit__(self, *exc) -> None: ...
